directories:
  output: release
  buildResources: build
appId: com.aiquant.trader
productName: AI Quant Trader
win:
  target:
    - nsis
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
extraResources:
  - from: ../../configs
    to: configs
  - from: ../../dist/backend_trader.exe
    to: dist/backend_trader.exe
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  runAfterFinish: true
electronVersion: 41.2.0
